#!/bin/bash

set -e

echo "--------------------------------------------------------------------------------"
echo "pre-commit hook started"
echo ""

make git-pre-commit

echo ""
echo "pre-commit hook OK"
echo "--------------------------------------------------------------------------------"
EOF