# Generated by Django 3.0.8 on 2020-10-12 03:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20201006_2326'),
        ('domain_config', '0006_auto_20201012_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Paused', 'Paused'), ('Finalized', 'Finalized')], default='Created', max_length=255)),
                ('location_as_string_reference', models.CharField(blank=True, max_length=255)),
                ('location_point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('domain_config', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.IncidentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_charge', models.BooleanField(default=False)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.Incident')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.SupervisorProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.Incident')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.ResourceProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
