# Generated by Django 3.0.8 on 2020-10-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0002_historicalincident_historicalincidentresource_historicalincidentsupervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='incident_visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_visibility',
            field=models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], default='Private', max_length=255),
        ),
    ]
