# Generated by Django 3.0.8 on 2020-10-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0003_auto_20201012_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalincident',
            old_name='incident_visibility',
            new_name='visibility',
        ),
        migrations.RenameField(
            model_name='incident',
            old_name='incident_visibility',
            new_name='visibility',
        ),
        migrations.AddField(
            model_name='historicalincident',
            name='data_status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='data_status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Complete', 'Complete')], default='Incomplete', max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalincident',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Canceled', 'Canceled'), ('Finalized', 'Finalized')], default='Started', max_length=255),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Canceled', 'Canceled'), ('Finalized', 'Finalized')], default='Started', max_length=255),
        ),
    ]
