# Generated by Django 3.0.8 on 2020-11-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0007_auto_20201110_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
