# Generated by Django 3.0.8 on 2020-11-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0008_auto_20201110_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalincident',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
