# Generated by Django 3.0.8 on 2021-02-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident', '0010_auto_20210208_0111'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incidentresource',
            constraint=models.UniqueConstraint(fields=('incident', 'resource'), name='Unique incident resource relation'),
        ),
    ]
