sudo: required
language: python
services:
  - docker
python:
  - "3.8"
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
before_script:
  - docker-compose build
script:
  - docker-compose run --rm web sh -c "flake8 . &&
    python wait_for_postgres.py &&
    ./manage.py test"
notifications:
  slack: tesis2020caba-ij78408:CBcouKtzlBEQaU8XxUmVgj0T

cache:
  pip: true
