version: '2'

services:
  postgres:
    image: postgres:11-alpine
    volumes:
      - data-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 15432:5432
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_dev
      - POSTGRES_CONN=postgresql://root:password@postgres:5432/db_dev
    image: web
    build: ./
    command: >
      sh -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  data-db: