version: '3.7'

services:
  postgis:
    image: kartoza/postgis:11.5-2.8
    volumes:
      - data-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_dev
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 15432:5432
    networks:
      SicoinNetwork:
        ipv4_address: 172.3.0.2
  web:
    image: web
    build: ./
    command: >
      sh -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgis
      - redis
    stdin_open: true
    tty: true
    networks:
      SicoinNetwork:
        ipv4_address: 172.3.0.3
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      SicoinNetwork:
        ipv4_address: 172.3.0.4
  redis:
    image: redis:6.0.6-alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      SicoinNetwork:
        ipv4_address: 172.3.0.5
volumes:
  data-db:
networks:
  SicoinNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.3.0.0/16