# Generated by Django 3.0.8 on 2020-09-22 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0003_domainconfig_domain_code'),
        ('users', '0002_auto_20171227_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='domain_config.SupervisorAlias')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig')),
                ('type', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='domain_config.ResourceType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
