# Generated by Django 3.0.8 on 2020-09-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0003_domainconfig_domain_code'),
        ('users', '0003_adminprofile_resourceprofile_supervisorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='domain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig'),
        ),
    ]
