# Generated by Django 3.0.8 on 2020-09-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0003_domainconfig_domain_code'),
        ('users', '0004_auto_20200922_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig'),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig'),
        ),
        migrations.AlterField(
            model_name='resourceprofile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.ResourceType'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='alias',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.SupervisorAlias'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig'),
        ),
    ]
