# Generated by Django 3.0.8 on 2020-12-29 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_django', '0005_auto_20170808_1145'),
        ('users', '0006_auto_20201006_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fcm_django.FCMDevice'),
        ),
    ]
