# Generated by Django 3.0.14 on 2021-05-24 22:28

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_resourceprofile_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceprofile',
            name='stats_by_incident',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
