# Generated by Django 3.0.8 on 2020-09-19 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain_name', models.CharField(max_length=255, unique=True)),
                ('admin_alias', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentAbstraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=255)),
                ('domain_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_config.DomainConfig')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('abstraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_config.IncidentAbstraction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupervisorAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.CharField(max_length=255)),
                ('domain_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_config.DomainConfig')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('domain_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_config.DomainConfig')),
            ],
        ),
        migrations.CreateModel(
            name='MapPointDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_config.IncidentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncidentTypeResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_config.IncidentType')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain_config.ResourceType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='supervisoralias',
            constraint=models.UniqueConstraint(fields=('domain_config', 'alias'), name='unique supervisor alias for a domain'),
        ),
        migrations.AddConstraint(
            model_name='resourcetype',
            constraint=models.UniqueConstraint(fields=('domain_config', 'name'), name='unique resource name for a domain'),
        ),
        migrations.AddConstraint(
            model_name='incidentabstraction',
            constraint=models.UniqueConstraint(fields=('domain_config', 'alias'), name='unique incident abstraction alias for domain_config'),
        ),
    ]
