# Generated by Django 3.0.8 on 2020-09-21 00:04

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0002_domainconfig_parsed_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainconfig',
            name='domain_code',
            field=encrypted_fields.fields.EncryptedCharField(help_text='Code used for domain-related tasks', max_length=255),
            preserve_default=False,
        ),
    ]
