# Generated by Django 3.0.8 on 2020-10-07 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0003_domainconfig_domain_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentabstraction',
            name='domain_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig'),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='abstraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.IncidentAbstraction'),
        ),
        migrations.AlterField(
            model_name='incidenttyperesources',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.IncidentType'),
        ),
        migrations.AlterField(
            model_name='incidenttyperesources',
            name='resource_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.ResourceType'),
        ),
        migrations.AlterField(
            model_name='mappointdescriptions',
            name='incident_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.IncidentType'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='domain_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig'),
        ),
        migrations.AlterField(
            model_name='supervisoralias',
            name='domain_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain_config.DomainConfig'),
        ),
    ]
