# Generated by Django 3.0.8 on 2020-10-08 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0004_auto_20201007_0133'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentTypeResources',
            new_name='IncidentTypeResource',
        ),
        migrations.RenameModel(
            old_name='MapPointDescriptions',
            new_name='MapPointDescription',
        ),
    ]
