# Generated by Django 3.0.8 on 2020-10-12 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0005_auto_20201008_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supervisoralias',
            options={'verbose_name_plural': 'Supervisor Aliases'},
        ),
    ]
