# Generated by Django 3.0.8 on 2020-10-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0007_incidenttype_details_schema'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='incidenttype',
            constraint=models.UniqueConstraint(fields=('name', 'abstraction'), name='unique incident type name for related abstraction'),
        ),
    ]
