# Generated by Django 3.0.8 on 2021-02-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0008_auto_20201025_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='is_able_to_contain_resources',
            field=models.BooleanField(default=False),
        ),
    ]
