# Generated by Django 3.0.14 on 2021-05-28 02:07

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain_config', '0009_resourcetype_is_able_to_contain_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttype',
            name='general_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
