# Generated by Django 3.0.8 on 2020-10-12 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident', '0001_initial'),
        ('geolocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackpoint',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.Incident'),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='incident_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.IncidentResource'),
        ),
        migrations.AddField(
            model_name='trackpoint',
            name='point_in_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geolocation.PointInTime'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.Incident'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='incident_resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='incident.IncidentResource'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='point_in_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geolocation.PointInTime'),
        ),
    ]
