name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
    steps:
    - uses: actions/checkout@v2
    - name: Build docker images
      run: docker-compose build
    - name: Run Tests
      run: |  
        docker-compose run --rm web sh -c "flake8 . &&
        python wait_for_postgres.py &&
        ./manage.py test"
